lib/dice_magick_web/router.ex
defmodule DiceMagickWeb.Router do
  @moduledoc false

  use DiceMagickWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  import Plug.BasicAuth
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {DiceMagickWeb.LayoutView, :root}
    plug DiceMagickWeb.Auth
  end

  pipeline :protected do
    # [todo] Configure username/password
    plug :basic_auth, username: "admin", password: "password"
  end

  if Mix.env() == :dev do
    scope "/" do
      pipe_through [:browser, :protected]
      live_dashboard "/dashboard", metrics: DiceMagickWeb.Telemetry
    end
  end

  scope "/", DiceMagickWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :delete]

    scope "/auth" do
      get "/:provider", SessionController, :request
      get "/:provider/callback", SessionController, :create
    end
  end

  scope "/manage", DiceMagickWeb do
    pipe_through [:browser, :authenticate_user]

    live "/characters/:id", CharacterLive.Show
    live "/characters/:id/edit", CharacterLive.Edit

    resources "/characters", CharacterController, only: [:index]
  end
end

lib/characters/process.ex
defmodule Characters.Process do
  @moduledoc """
  Handles fetching and updating roll data for a character.
  """

  use GenServer

  require Logger

  alias Characters

  @update_time 60_000

  defmodule State do
    @moduledoc """
    State for a character process.
    """

    @type t :: %__MODULE__{}
    defstruct [
      :character,
      :source_module,
      :source_type,
      :last_updated,
      source_params: %{},
      source_data: %{}
    ]
  end

  @doc """
  Starts a new character process.
  """
  def start_link(character_id) do
    GenServer.start_link(__MODULE__, character_id, name: pid(character_id))
  end

  defp pid(id), do: {:global, {__MODULE__, id}}

  defp schedule_update(time), do: Process.send_after(self(), :update, time)

  #
  # Client
  #

  @doc """
  Returns the state of the process.
  """
  def state(id), do: GenServer.call(pid(id), :state)

  @doc """
  Fetches new data from the character's `source`, and updates that character's roll's.
  """
  def update(id), do: GenServer.cast(pid(id), :update)

  #
  # Callbacks
  #

  @impl true
  def init(character_id) do
    character = Characters.get_character!(character_id, preload: [:rolls])
    %{source_type: type, source_params: params} = character

    state = %State{
      character: character,
      source_module: Characters.source_for_type(type),
      source_type: type,
      source_params: params,
      source_data: %{}
    }

        Process.send(self(), :update, [])

    Logger.log(:info, "Initialized process for #{character.name}")

    {:ok, state}
  end

  @impl true
  def handle_call(:state, _from, state), do: {:reply, state, state}

  @impl true
  def handle_cast(:update, state) do
    Process.send(self(), :update, [])
    {:noreply, state}
  end

  @impl true
  def handle_info(:update, state) do
    %{character: character, source_module: module, source_params: params} = state
    {:ok, fresh_data} = module.fetch_data(params)
    {:ok, rolls} = module.generate_rolls(fresh_data)

    rolls =
      Enum.map(rolls, fn roll ->
        roll
        |> Map.delete(:tags)
        |> Map.put(:character_id, character.id)
      end)

    Characters.update_character(character, %{rolls: rolls}) |> IO.inspect()
    new_state = %{state | source_data: fresh_data, last_updated: DateTime.utc_now()}

    Logger.log(:info, "Updated rolls for #{character.name}")

    schedule_update(@update_time)

    {:noreply, new_state}
  end
end

lib/dice_magick/characters.ex
defmodule DiceMagick.Characters do
  @moduledoc """
  The Characters context.
  """

  alias DiceMagick.{Characters, Repo, Sources}
  alias DiceMagick.Characters.Character
  alias DiceMagick.Accounts.User

  import Ecto.Query

  @type repo_result :: {:ok, Character.t()} | {:error, Ecto.Changeset.t()}

  @doc """
  Returns the list of `DiceMagick.Characters.Character`s for a
  `DiceMagick.Accounts.User`.

  ## Examples

      iex> list_characters_for_user(user)
      [%Character{}, ...]

  """
  @spec list_characters_for_user(User.t()) :: [Character.t()]
  def list_characters_for_user(%User{id: user_id}) do
    Character
    |> where(user_id: ^user_id)
    |> Repo.all()
  end

  @doc """
  Gets a single `DiceMagick.Characters.Character`.

  Raises `Ecto.NoResultsError` if the `Character` does not exist.

  ## Options

    * `preload` - Specifies which associations, if any, to preload

  ## Examples

      iex> get_character!("123", preload: [:roll_results])
      %Character{}

      iex> get_character!("456")
      ** (Ecto.NoResultsError)

  """
  @spec get_character!(Ecto.UUID.t(), [{:preload, atom | [atom] | Keyword.t()}]) :: Character.t()
  def get_character!(id, opts \\ []) do
    preload = Keyword.get(opts, :preload, [])

    Character
    |> Repo.get!(id)
    |> Repo.preload(preload)
  end

  @doc """
  Creates a `DiceMagick.Characters.Character`. On success, starts a new
  `DiceMagick.Characters.Worker` for the character.

  ## Examples

      iex> create_character(%{field: value})
      {:ok, %Character{}}

      iex> create_character(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  @spec create_character(map) :: repo_result
  def create_character(attrs \\ %{}) do
    %Character{}
    |> Character.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a `DiceMagick.Characters.Character`.

  ## Examples

      iex> update_character(character, %{field: new_value})
      {:ok, %Character{}}

      iex> update_character(character, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  @spec update_character(Character.t(), map) :: {:ok, Character.t()} | {:error, Changeset.t()}
  def update_character(%Character{} = character, attrs) do
    character
    |> Character.changeset(attrs)
    |> Repo.update()
    |> maybe_notify_worker(attrs)
  end

  @spec maybe_notify_worker(repo_result, map) :: repo_result
  defp maybe_notify_worker({:ok, character} = result, %{source_params: _}) do
    Characters.Worker.update(character.id)
    result
  end

  defp maybe_notify_worker(result, _attrs), do: result

  @doc """
  Deletes a `DiceMagick.Characters.Character`.

  ## Examples

      iex> delete_character(character)
      {:ok, %Character{}}

      iex> delete_character(character)
      {:error, %Ecto.Changeset{}}

  """
  @spec delete_character(Character.t()) :: {:ok, Character.t()} | {:error, Changeset.t()}
  def delete_character(%Character{} = character), do: Repo.delete(character)

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking `DiceMagick.Characters.Character`
  changes.

  ## Examples

      iex> change_character(character)
      %Ecto.Changeset{data: %Character{}}

  """
  @spec change_character(Character.t(), map) :: Changeset.t()
  def change_character(%Character{} = character, attrs \\ %{}) do
    Character.changeset(character, attrs)
  end

  @doc """
  Given a `SourceTypeEnum`, returns the module for that type.
  """
  @spec source_for_type(atom) :: atom
  def source_for_type(:test), do: Sources.Test
  def source_for_type(:google_sheets), do: Sources.GoogleSheets
  def source_for_type(:tintagel_5e), do: Sources.Tintagel5E

  @doc """
  Gets the `DiceMagick.Characters.Character` for the given `discord_uid` and
  `discord_channel_id`.

  Returns `nil` if no such `Character` is found.

  ## Examples

      iex> get_character_for_channel("123456", "7890101")
      %Character{}

      iex> get_character_for_channel("654321", "7890101")
      nil

  """
  @spec get_character_for_channel(String.t(), String.t()) :: Character.t() | nil
  def get_character_for_channel(discord_uid, discord_channel_id) do
    query =
      from c in Character,
        join: u in User,
        on: u.id == c.user_id,
        where: u.discord_uid == ^discord_uid,
        where: c.discord_channel_id == ^discord_channel_id,
        limit: 1

    Repo.one(query)
  end
end

lib/dice_magick/characters/character.ex
defmodule DiceMagick.Characters.Character do
  @moduledoc """
  A `DiceMagick.Accounts.User`’s character in a Discord channel.

  ## Fields

    * `name` - The `Character`’s name
    * `source_type` - The source from which to fetch rolls
    * `source_params` - Specifies how to fetch rolls from the source
    * `discord_channel_id` - Indicates the Discord channel this `Character` belongs to
    * `archetype` - The particular TTRPG this character exists in
    * `color` - A color used to help identify the character in the app and Discord channel

  ## Associations

    * `user` - The `User` that the `Character` belongs to

  ## Validations

    * `user_id` - Required
    * `name` - Required, unique per `user_id`
    * `discord_channel_id` - Required, unique per `user_id`
    * `source_params` - Validated based on the `source_type`

  """

  use DiceMagick.Schema
  import Ecto.Changeset

  alias DiceMagick.Accounts.User
  alias Ecto.Changeset

  schema "characters" do
    field :name, :string
    field :source_type, SourceTypeEnum
    field :source_params, :map
    field :discord_channel_id, :string
    field :archetype, ArchetypeEnum
    field :color, :string, default: "#ca4548"

    belongs_to :user, User

    has_many :roll_results, DiceMagick.Rolls.Result

    timestamps()
  end

  @doc false
  def changeset(%__MODULE__{} = character, params) do
    character
    |> cast(params, [
      :name,
      :source_type,
      :source_params,
      :discord_channel_id,
      :archetype,
      :user_id,
      :color
    ])
    |> validate_required([:name, :discord_channel_id, :user_id, :color])
    |> validate_source_params()
    |> assoc_constraint(:user)
    |> unique_constraint([:discord_channel_id, :user_id])
    |> unique_constraint([:name, :user_id])
  end

  @spec validate_source_params(Changeset.t()) :: Changeset.t()
  defp validate_source_params(%Changeset{changes: %{source_params: params}} = chset) do
    module =
      chset
      |> Changeset.get_field(:source_type)
      |> DiceMagick.Characters.source_for_type()

    case module.validate_params(params) do
      :ok -> chset
      {:error, errors} -> Enum.reduce(errors, chset, &add_error(&2, :source_params, &1))
    end
  end

  defp validate_source_params(%Changeset{} = chset), do: chset
end

lib/dice_magick/characters/supervisor.ex
defmodule DiceMagick.Characters.Supervisor do
  @moduledoc """
  Supervises `DiceMagick.Characters.CharacterWorker`s.
  """

  use DynamicSupervisor

  alias DiceMagick.Characters.Worker

  def start_link(_arg) do
    DynamicSupervisor.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  @impl true
  def init(:ok) do
    DynamicSupervisor.init(strategy: :one_for_one)
  end

  @spec add_worker(Ecto.UUID.t()) :: :ok | :noop
  def add_worker(id) do
    worker_name = Worker.name(id)

    case GenServer.whereis(worker_name) do
      nil ->
        child_spec = {Worker, character_id: id}
        DynamicSupervisor.start_child(__MODULE__, child_spec)

      _ ->
        :noop
    end
  end

  def ensure_started(id), do: add_worker(id)
end

lib/dice_magick/characters/worker.ex
defmodule DiceMagick.Characters.Worker do
  @moduledoc """
  Client/server for fetching and updating a `DiceMagick.Characters.Character`'s
  `DiceMagick.Rolls.Roll`s.
  """

  use GenServer

  require Logger

  alias DiceMagick.Characters
  alias DiceMagick.Rolls.Roll
  alias Ecto.UUID

  defmodule State do
    @moduledoc """
    State for a worker process.
    """

    @type t() :: %__MODULE__{}
    defstruct [
      :character_id,
      :synced_at,
      rolls: [],
      tags: []
    ]
  end

  @doc """
  Starts a new worker process.

  ## Options

    * `character_id` - The UUID of the `DiceMagick.Characters.Character` (required)
    * `state` - The initial state for the worker

  """
  @spec start_link(Keyword.t()) :: :ignore | {:error, term} | {:ok, pid}
  def start_link(opts) do
    character_id = Keyword.fetch!(opts, :character_id)

    state_fields =
      opts
      |> Keyword.get(:state, %{})
      |> Map.put(:character_id, character_id)

    state = struct!(State, state_fields)

    GenServer.start_link(__MODULE__, state, name: name(character_id))
  end

  ## Client

  @doc """
  Returns the name of the registered process for the given `character_id`.
  """
  @spec name(UUID.t()) :: {:global, {atom(), UUID.t()}}
  def name(character_id), do: {:global, {__MODULE__, character_id}}

  @doc """
  Returns the state of the worker process.
  """
  @spec state(String.t()) :: State.t()
  def state(character_id) do
    Characters.Supervisor.ensure_started(character_id)
    GenServer.call(name(character_id), :state)
  end

  @doc """
  Fetches new data from the `DiceMagick.Characters.Character`'s `source`, and
  updates that character's `DiceMagick.Rolls.Roll`s.
  """
  @spec update(String.t()) :: :ok
  def update(character_id) do
    Characters.Supervisor.ensure_started(character_id)
    GenServer.cast(name(character_id), :update)
  end

  @doc """
  Similar to `update/1`, but performs the task synchronously.
  """
  @spec update_sync(String.t()) :: State.t()
  def update_sync(character_id) do
    Characters.Supervisor.ensure_started(character_id)
    GenServer.call(name(character_id), :update)
  end

  @doc """
  Stops a worker process.
  """
  @spec stop(String.t()) :: :ok
  def stop(character_id), do: GenServer.cast(name(character_id), :stop)

  ## Server callbacks

  @impl true
  def init(%{character_id: character_id} = state) do
    Logger.log(:info, "Initialized process for Character #{character_id}")
    Process.send(self(), :update, [])
    {:ok, state}
  end

  @impl true
  def handle_call(:state, _from, state), do: {:reply, state, state}

  @impl true
  def handle_call(:update, _from, state) do
    new_state = update_state(state)
    {:reply, new_state, new_state}
  end

  @impl true
  def handle_cast(:update, state) do
    Process.send(self(), :update, [])
    {:noreply, state}
  end

  @impl true
  def handle_cast(:stop, state), do: {:stop, :normal, state}

  @impl true
  def handle_info(:update, state) do
    new_state = update_state(state)
    # schedule_update(@update_time)
    {:noreply, new_state}
  end

  ## Helpers

  @spec update_state(State.t()) :: State.t()
  defp update_state(%{character_id: character_id} = state) do
    character = Characters.get_character!(character_id)

    case character.source_type do
      nil ->
        state

      type ->
        module = Characters.source_for_type(type)

        {:ok, data} = module.fetch_data(character.source_params)
        {:ok, rolls} = module.generate_rolls(data)
        rolls = Enum.map(rolls, &%Roll{&1 | character_id: character_id})

        tags = tags_from_rolls(rolls)

        %{state | rolls: rolls, tags: tags, synced_at: DateTime.utc_now()}
    end
  end

  @spec tags_from_rolls([Roll.t()]) :: [String.t()]
  defp tags_from_rolls(rolls) do
    rolls
    |> Enum.flat_map(& &1.tags)
    |> Enum.uniq()
  end
end

lib/dice_magick_web/controllers/character_controller.ex
defmodule DiceMagickWeb.CharacterController do
  use DiceMagickWeb, :controller
  alias DiceMagick.Characters

  def index(conn, _) do
    %{assigns: %{current_user: current_user}} = conn
    characters = Characters.list_characters_for_user(current_user)
    render(conn, "index.html", characters: characters)
  end

  def show(conn, %{"id" => id}) do
    %{assigns: %{current_user: current_user}} = conn
    character = Characters.get_character!(id, preload: [:rolls, :tags])

    if character.user_id == current_user.id do
      render(conn, "show.html", character: character)
    else
      conn
      |> text("That doesn’t belong to you.")
      |> halt()
    end
  end
end

lib/dice_magick_web/views/character_view.ex
defmodule DiceMagickWeb.CharacterView do
  @moduledoc false
  use DiceMagickWeb, :view
  alias DiceMagickWeb.CharacterLive
end

lib/dice_magick_web/templates/character/card.html.eex
<%= link @character.name %>

lib/dice_magick_web/templates/character/edit.html.leex
<section>
  <h1 >Edit <%= @character.name %></h1>
  <%= render "form.html", assigns %>
  <%= link to: Routes.live_path(@socket, CharacterLive.Show, @character), class: "link link--secondary text-sm" do %>
    Never mind
  <% end %>
</section>

lib/dice_magick_web/templates/character/form.html.leex
<%= f = form_for @changeset, "#", [phx_change: :update, phx_submit: :save] %>
<%= text_input f, :name, placeholder: "Name", class: "input", required: true %>
<%= select f, :source_type, ["Google Sheets": :google_sheets] %>

<input type="text" name="key" value="<%= @key %>" placeholder="Spreadsheet key"  required />
<input type="text" name="worksheet" value="<%= @worksheet %>" placeholder="Worksheet"  required />

<%= submit do %>Save<% end %>
</form>

lib/dice_magick_web/templates/character/index.html.eex
<section>
  <h1>Your Characters</h1>
  <%= if Enum.empty?(@characters) do %>
    <p>Looks like no one’s home.</p>
  <% else %>
    <ul>
      <%= for character <- @characters do %>
        <li><%= link character.name, to: Routes.live_path(@conn, CharacterLive.Show, character), class: "link" %></li>
      <% end %>
    </ul>
  <% end %>
</section>

lib/dice_magick_web/templates/character/new.html.leex
<section>
  <h1>Create a Character</h1>

  <div>
    <%= render "form.html", assigns %>
  </div>

  <%= link to: Routes.character_path(@socket, :index) do %>
    Never mind
  <% end %>
</section>

lib/dice_magick_web/templates/character/pinned_rolls.html.leex
<div>
  <%= for roll <- @rolls do %>
    <button phx-click="roll" phx-value-name="<%= roll.name %>">
      <%= if roll.favorite do %>
        <span >✭</span>
      <% else %>
        <span >✩</span>
      <% end %>
      <%= roll.name %>
    </button>
  <% end %>
</div>

lib/dice_magick_web/templates/character/show.html.leex
<div class="flex min-h-screen">
  <%= live_component(@socket,
        DiceMagickWeb.CharacterLive.SidebarComponent,
        character: @character, synced_at: @synced_at) %>

  <div class="flex-1">
    <div class="relative pt-24 pb-12 px-16 bg-slate-100 bg-opacity-2">
      <div class="flex mb-8 space-x-3">
        <%= live_component(@socket,
              DiceMagickWeb.CharacterLive.TagsComponent,
              tags: @tags) %>
      </div>

      <div class="pinned-rolls">
        <%= live_component(@socket,
              DiceMagickWeb.CharacterLive.RollsComponent, rolls: elem(@grouped_rolls, 0)) %>
      </div>

      <div class="magick-circle"></div>
    </div>

    <div class="pl-16 pt-12 pb-24 flex">
      <div class="rolls mr-6 grid grid-cols-4 gap-5">
        <%= live_component(@socket,
              DiceMagickWeb.CharacterLive.RollsComponent,
                rolls: elem(@grouped_rolls, 1) -- elem(@grouped_rolls, 0)) %>
      </div>

      <div class="flex-1">
        <%= live_component(@socket,
              DiceMagickWeb.CharacterLive.RecentResultsComponent,
              results: @results) %>
      </div>
    </div>
  </div>
</div>

<style id="primary-color">:root { --primary: <%= @character.color %> }</style>

lib/dice_magick_web/templates/character/sidebar.html.leex
<section class="sidebar">
  <div class="sidebar__character">
    <img class="sidebar__avatar" src="/images/dust.png" />
    <div class="sidebar__color"></div>
  </div>

  <h1 class="sidebar__name">
    Dust the Archivist
    <%# <%= link @character.name, to: Routes.live_path(@socket, CharacterLive.Edit, @character) %1> %>
  </h1>

  <div class="sidebar__info">
    <dl>
      <dt>Source:</dt>
      <dd>
      <%= link "Google Sheets", target: "_blank", to: "https://docs.google.com/spreadsheets/d/#{@character.source_params["key"]}" %>
      </dd>
    </dl>

    <dl>
      <dt>Updated:</dt>
      <dd><%= @synced_at %></dd>
    </dl>
  </div>

  <button phx-click="sync" phx-throttle="3000">
    Sync Rolls
  </button>
</section>

lib/dice_magick_web/templates/character/tags.html.leex
  <%= for tag <- @tags do %>
    <button
      class="tag"
        phx-value-tag="<%= tag %>"
        phx-click="apply-tag">
        <%= tag %>
      </button>
  <% end %>